testing: 0

dataset: './data/arxiv_dataset_50k.json'

abstract_dataset: './data/abstract_arxiv_dataset_50k.json'
title_dataset: './data/title_arxiv_dataset_50k.json'

search_engine:
  reindex: False

parser:
  subtree: True
  nouns:
    nsubj: True
    nsubjpass: True
    pobj: False
    dobj: False
